begin;
select plan(16);
select has_function('internal','credential_template_validation_issues',array['uuid'],'private structural validator should exist');
select has_function('public','validate_credential_template_version',array['uuid'],'guarded validation function should exist');
select has_function('public','update_credential_template_document',array['uuid','uuid','uuid','text','text','integer','boolean'],'atomic document update should exist');
select has_function('public','replace_credential_template_document_placements',array['uuid','uuid','jsonb'],'atomic placement replacement should exist');
select has_function('public','record_credential_template_preview',array['uuid'],'privacy-minimal preview audit should exist');
select results_eq($$select has_function_privilege('anon','public.validate_credential_template_version(uuid)'::regprocedure,'execute')$$,$$values(false)$$,'anonymous validation should be denied');
select results_eq($$select has_function_privilege('authenticated','public.validate_credential_template_version(uuid)'::regprocedure,'execute')$$,$$values(true)$$,'authenticated validation reaches the role/MFA guard');
select results_eq($$select has_function_privilege('anon','public.replace_credential_template_document_placements(uuid,uuid,jsonb)'::regprocedure,'execute')$$,$$values(false)$$,'anonymous placement writes should be denied');
select results_eq($$select has_function_privilege('authenticated','public.replace_credential_template_document_placements(uuid,uuid,jsonb)'::regprocedure,'execute')$$,$$values(true)$$,'authenticated placement writes reach the role/MFA guard');
select results_eq($$select has_function_privilege('anon','public.record_credential_template_preview(uuid)'::regprocedure,'execute')$$,$$values(false)$$,'anonymous preview audit should be denied');
select results_eq($$select count(*)::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('validate_credential_template_version','update_credential_template_document','replace_credential_template_document_placements','record_credential_template_preview','publish_credential_template_version') and pg_get_functiondef(p.oid) like '%internal.assert_sensitive_action_allowed%' and pg_get_functiondef(p.oid) like '%owner%' and pg_get_functiondef(p.oid) like '%super_admin%'$$,$$values(5::bigint)$$,'all editor mutations require Owner/Super Admin and MFA');
select results_eq($$select count(*)::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='publish_credential_template_version' and pg_get_functiondef(p.oid) like '%credential_template_validation_issues%'$$,$$values(1::bigint)$$,'publication must use structural validation');
select results_eq($$select enumlabel::text from pg_enum where enumtypid='public.credential_template_field_key'::regtype order by enumsortorder$$,$$values('holder_name'),('programme_title'),('credential_type'),('document_number'),('issue_date'),('completion_date'),('programme_run_label'),('verification_qr'),('verification_url'),('static_text')$$,'field vocabulary stays constrained');
select results_eq($$select enumlabel::text from pg_enum where enumtypid='public.credential_template_version_status'::regtype order by enumsortorder$$,$$values('draft'),('published'),('retired')$$,'version lifecycle stays constrained');
select results_eq($$select enumlabel::text from pg_enum where enumtypid='public.credential_status'::regtype order by enumsortorder$$,$$values('pending'),('valid'),('revoked'),('voided')$$,'credential lifecycle is unchanged');
select results_eq($$select count(*)::bigint from information_schema.columns where table_schema='public' and table_name like 'credential_template%' and column_name like '%sample%'$$,$$values(0::bigint)$$,'fictional preview values are never persisted');
select * from finish();
rollback;
