import 'server-only';
/* eslint-disable @typescript-eslint/no-explicit-any */
import type { SupabaseClient } from '@supabase/supabase-js';
import { ApiError, assertCanManageCredentialTemplates, getSupabaseRequestClient, type AdminContext } from '@/lib/supabase/server';
import type { TemplateDocument, TemplatePackage, TemplatePlacement, TemplateValidation, TemplateWorkspace } from './admin-types';

function db(context:AdminContext):SupabaseClient{assertCanManageCredentialTemplates(context);return getSupabaseRequestClient(context.accessToken);}
function failure(error:{code?:string;message?:string;details?:string}|null,message:string){if(error?.code==='42501')return new ApiError('forbidden',403,message);if(error?.code==='P0002')return new ApiError('not_found',404,message);if(['22023','22P02','23503','23514'].includes(error?.code??''))return new ApiError('bad_request',400,error?.message||message);if(error?.code==='23505')return new ApiError('conflict',409,error.message||message);return new ApiError('server_error',500,message);}
const packageColumns='id, programme_id, programme_run_id, credential_type_id, language_code, variant_code, display_name, created_at';
const versionColumns='id, template_package_id, version_number, status, published_at, retired_at, created_at';
const documentColumns='id, template_version_id, file_type_id, admin_label, output_filename_pattern, sort_order, is_primary, mime_type, size_bytes, page_count, created_at, updated_at';
const placementColumns='id, template_document_id, page_number, field_key, occurrence_order, x_points, y_points, width_points, height_points, font_family, font_size_points, min_font_size_points, font_weight, font_color, text_alignment, fit_mode, date_format, static_text, is_required';
function placement(row:any):TemplatePlacement{return {id:row.id,pageNumber:Number(row.page_number),fieldKey:row.field_key,occurrenceOrder:Number(row.occurrence_order),xPoints:Number(row.x_points),yPoints:Number(row.y_points),widthPoints:Number(row.width_points),heightPoints:Number(row.height_points),fontFamily:row.font_family,fontSizePoints:row.font_size_points===null?null:Number(row.font_size_points),minFontSizePoints:row.min_font_size_points===null?null:Number(row.min_font_size_points),fontWeight:row.font_weight,fontColor:row.font_color,textAlignment:row.text_alignment,fitMode:row.fit_mode,dateFormat:row.date_format,staticText:row.static_text,isRequired:row.is_required};}
function document(row:any,pages:any[],placements:any[]):TemplateDocument{return {id:row.id,templateVersionId:row.template_version_id,fileTypeId:row.file_type_id,adminLabel:row.admin_label,outputFilenamePattern:row.output_filename_pattern,sortOrder:row.sort_order,isPrimary:row.is_primary,mimeType:row.mime_type,sizeBytes:Number(row.size_bytes),pageCount:row.page_count,createdAt:row.created_at,updatedAt:row.updated_at,pages:pages.filter(p=>p.template_document_id===row.id).map(p=>({pageNumber:p.page_number,widthPoints:Number(p.width_points),heightPoints:Number(p.height_points)})),placements:placements.filter(p=>p.template_document_id===row.id).map(placement)};}
export async function workspace(context:AdminContext):Promise<TemplateWorkspace>{const client=db(context);const results=await Promise.all([
 client.from('credential_template_packages').select(packageColumns).order('created_at',{ascending:false}),client.from('credential_template_versions').select(versionColumns).order('version_number',{ascending:false}),client.from('credential_template_documents').select(documentColumns).order('sort_order'),client.from('credential_template_document_pages').select('template_document_id, page_number, width_points, height_points').order('page_number'),client.from('credential_template_field_placements').select(placementColumns).order('occurrence_order'),client.from('programmes').select('id, slug').order('slug'),client.from('programme_translations').select('programme_id, title').eq('language_code','en'),client.from('programme_runs').select('id, programme_id, status, starts_at, ends_at').order('starts_at'),client.from('credential_types').select('id, code').eq('is_active',true).order('code'),client.from('credential_type_translations').select('credential_type_id, display_name').eq('language_code','en'),client.from('credential_file_types').select('id, code, default_label').eq('is_active',true).order('code'),client.from('languages').select('code, name').eq('is_active',true).order('sort_order')]);
 for(const result of results)if(result.error)throw failure(result.error,'Template workspace could not be loaded.');const [packages,versions,documents,pages,placements,programmes,translations,runs,types,typeTranslations,fileTypes,languages]=results.map(r=>r.data??[]);const pt=new Map((translations as any[]).map(r=>[r.programme_id,r.title]));const ct=new Map((typeTranslations as any[]).map(r=>[r.credential_type_id,r.display_name]));
 return {packages:(packages as any[]).map(row=>({id:row.id,programmeId:row.programme_id,programmeRunId:row.programme_run_id,credentialTypeId:row.credential_type_id,languageCode:row.language_code,variantCode:row.variant_code,displayName:row.display_name,createdAt:row.created_at,versions:(versions as any[]).filter(v=>v.template_package_id===row.id).map(v=>({id:v.id,packageId:v.template_package_id,versionNumber:v.version_number,status:v.status,publishedAt:v.published_at,retiredAt:v.retired_at,createdAt:v.created_at,documents:(documents as any[]).filter(d=>d.template_version_id===v.id).map(d=>document(d,pages as any[],placements as any[]))}))})) as TemplatePackage[],references:{programmes:(programmes as any[]).map(r=>({id:r.id,label:pt.get(r.id)??r.slug})),programmeRuns:(runs as any[]).map(r=>({id:r.id,programmeId:r.programme_id,label:`${r.status}${r.starts_at?` · ${r.starts_at}`:''}${r.ends_at?` — ${r.ends_at}`:''}`})),credentialTypes:(types as any[]).map(r=>({id:r.id,label:ct.get(r.id)??r.code})),fileTypes:(fileTypes as any[]).map(r=>({id:r.id,code:r.code,label:r.default_label})),languages:(languages as any[]).map(r=>({code:r.code,label:r.name}))}};}
export async function createPackage(context:AdminContext,input:any){const client=db(context);const {data,error}=await client.rpc('create_credential_template_package',{p_programme_id:input.programmeId,p_programme_run_id:input.programmeRunId,p_credential_type_id:input.credentialTypeId,p_language_code:input.languageCode,p_variant_code:input.variantCode,p_display_name:input.displayName});if(error)throw failure(error,'Template package could not be created.');return (data as any[])?.[0];}
export async function createVersion(context:AdminContext,packageId:string){const {data,error}=await db(context).rpc('create_credential_template_version',{p_template_package_id:packageId});if(error)throw failure(error,'Draft version could not be created.');return data as string;}
export async function saveDocument(context:AdminContext,versionId:string,documentId:string,input:any){const {data,error}=await db(context).rpc('update_credential_template_document',{p_template_version_id:versionId,p_document_id:documentId,p_file_type_id:input.fileTypeId,p_admin_label:input.adminLabel,p_output_filename_pattern:input.outputFilenamePattern,p_sort_order:input.sortOrder,p_is_primary:input.isPrimary});if(error)throw failure(error,'Document metadata could not be saved.');return (data as any[])?.[0];}
export async function savePlacements(context:AdminContext,versionId:string,documentId:string,items:TemplatePlacement[]){const payload=items.map(p=>({page_number:p.pageNumber,field_key:p.fieldKey,occurrence_order:p.occurrenceOrder,x_points:p.xPoints,y_points:p.yPoints,width_points:p.widthPoints,height_points:p.heightPoints,font_family:p.fontFamily,font_size_points:p.fontSizePoints,min_font_size_points:p.minFontSizePoints,font_weight:p.fontWeight,font_color:p.fontColor,text_alignment:p.textAlignment,fit_mode:p.fitMode,date_format:p.dateFormat,static_text:p.staticText,is_required:p.isRequired}));const {error}=await db(context).rpc('replace_credential_template_document_placements',{p_template_version_id:versionId,p_template_document_id:documentId,p_placements:payload});if(error)throw failure(error,'Field placements could not be saved.');}
export async function validateVersion(context:AdminContext,versionId:string):Promise<TemplateValidation>{const {data,error}=await db(context).rpc('validate_credential_template_version',{p_template_version_id:versionId});if(error)throw failure(error,'Template version could not be validated.');return data as TemplateValidation;}
export async function versionAction(context:AdminContext,versionId:string,action:'publish'|'retire'|'preview'){const rpc=action==='publish'?'publish_credential_template_version':action==='retire'?'retire_credential_template_version':'record_credential_template_preview';const {data,error}=await db(context).rpc(rpc,{p_template_version_id:versionId});if(error)throw failure(error,`Template version could not be ${action}ed.`);return data;}
