import { ApiError } from '@/lib/supabase/server';
import { assertUuid } from '@/lib/learners/admin-input';
import { templateFieldKeys, type TemplatePlacement } from './admin-types';

function object(value:unknown):Record<string,unknown>{ if(!value||typeof value!=='object'||Array.isArray(value)) throw new ApiError('bad_request',400,'A JSON object is required.'); return value as Record<string,unknown>; }
function text(value:unknown,name:string,max=255){ if(typeof value!=='string'||!value.trim()||value.trim().length>max) throw new ApiError('bad_request',400,`${name} is required or invalid.`); return value.trim(); }
function number(value:unknown,name:string,min=0){ if(typeof value!=='number'||!Number.isFinite(value)||value<min) throw new ApiError('bad_request',400,`${name} is invalid.`); return value; }
export async function jsonBody(request:Request){ try{return object(await request.json());}catch(error){if(error instanceof ApiError)throw error;throw new ApiError('bad_request',400,'Valid JSON is required.');} }
export function packageInput(v:Record<string,unknown>){return {programmeId:assertUuid(text(v.programmeId,'Programme ID',36),'programme ID'),programmeRunId:v.programmeRunId?assertUuid(text(v.programmeRunId,'Programme run ID',36),'programme run ID'):null,credentialTypeId:assertUuid(text(v.credentialTypeId,'Credential type ID',36),'credential type ID'),languageCode:text(v.languageCode,'Language code',8).toLowerCase(),variantCode:text(v.variantCode,'Variant code',64).toLowerCase(),displayName:text(v.displayName,'Display name',200)};}
export function documentInput(v:Record<string,unknown>){const pattern=text(v.outputFilenamePattern,'Output filename',255);if(!pattern.toLowerCase().endsWith('.pdf')||/[\\/\r\n]/.test(pattern))throw new ApiError('bad_request',400,'Output filename must be a safe PDF filename.');return {fileTypeId:assertUuid(text(v.fileTypeId,'File type ID',36),'file type ID'),adminLabel:text(v.adminLabel,'Admin label',255),outputFilenamePattern:pattern,sortOrder:number(v.sortOrder,'Sort order'),isPrimary:v.isPrimary===true};}
export function placementsInput(v:Record<string,unknown>):TemplatePlacement[]{if(!Array.isArray(v.placements)||v.placements.length>250)throw new ApiError('bad_request',400,'Placements must be an array of at most 250 items.');return v.placements.map((raw,index)=>{const p=object(raw);const key=text(p.fieldKey,`Field ${index+1}`,30);if(!templateFieldKeys.includes(key as never))throw new ApiError('bad_request',400,`Field ${index+1} is not allowed.`);const qr=key==='verification_qr';return {pageNumber:number(p.pageNumber,'Page number',1),fieldKey:key as TemplatePlacement['fieldKey'],occurrenceOrder:number(p.occurrenceOrder,'Occurrence order'),xPoints:number(p.xPoints,'X'),yPoints:number(p.yPoints,'Y'),widthPoints:number(p.widthPoints,'Width',0.001),heightPoints:number(p.heightPoints,'Height',0.001),fontFamily:qr?null:'noto_sans',fontSizePoints:qr?null:number(p.fontSizePoints,'Font size',1),minFontSizePoints:qr?null:number(p.minFontSizePoints,'Minimum font size',1),fontWeight:qr?null:number(p.fontWeight,'Font weight',100),fontColor:qr?null:text(p.fontColor,'Font colour',7),textAlignment:['left','center','right'].includes(String(p.textAlignment))?p.textAlignment as TemplatePlacement['textAlignment']:'left',fitMode:qr?'fixed':(['single_line','wrap','shrink_to_fit'].includes(String(p.fitMode))?p.fitMode as TemplatePlacement['fitMode']:'shrink_to_fit'),dateFormat:(key==='issue_date'||key==='completion_date')?text(p.dateFormat??'DD.MM.YYYY','Date format',64):null,staticText:key==='static_text'?text(p.staticText,'Static text',2000):null,isRequired:p.isRequired!==false};});}
